name: flutter_chat_app
description: "Chating App using Firebase"
publish_to: 'none' # private project, not for pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/logo.jpg
    - assets/icons/

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_auth: any
  cloud_firestore: any
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  flutter_launcher_icons: ^0.11.0

# Launcher icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/chat_icon.png"
